version: '2'
services:
  slate-serve:
    build:
      context: .
    image: pluginsdotdev-docs
    user: ${CURRENT_USER}
    ports:
      - "9001:4567"
    volumes:
      - ".:/usr/src/docs:ro"
    command: ["/usr/src/docs/scripts/serve"]
  slate-build:
    build:
      context: .
    image: pluginsdotdev-docs
    user: ${CURRENT_USER}
    volumes:
      - ".:/usr/src/docs:ro"
      - "./dist:/usr/src/app/build"
    command: ["/usr/src/docs/scripts/build"]
