#!/bin/bash -e

root="$(readlink -f "$(dirname $0)/..")"

USER="${CURRENT_USER:-$UID}"

# build slate docs
cd "${root}/packages/docs"
CURRENT_USER="$USER" docker-compose run --rm slate-build

# build all other docs
cd "${root}"
CURRENT_USER="$USER" docker-compose run --rm npm run lerna run build-docs

# coalesce
rm -rf "${root}/docs"
cp -r "${root}/packages/docs/dist" "${root}/docs"
cp "${root}/packages/docs/favicon.ico" "${root}"
for doc in ${root}/packages/*/docs;
do
  if [ -d "${doc}" ]; then
    package_name="$(basename "$(dirname "${doc}")")"
    api_dir="${root}/docs/api/${package_name}"
    mkdir -p "${api_dir}"
    cp -r "${doc}" "${api_dir}"
  fi
done
