name: Build-Docs

on:
  push:
    tags: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm ci
      - run: npm run bootstrap-ci
      - run: npm run build
      - run: $GITHUB_WORKSPACE/scripts/build-docs
        env:
          CURRENT_USER: 0
      - name: Share artifact inside workflow
        uses: actions/upload-artifact@v1
        with:
          name: static-assets
          path: ./docs
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: destination
        shell: bash
        run: echo "::set-output name=dest::$(if [ \"${GITHUB_REF#refs/heads/}\" == \"master\" ]; then echo \"latest\"; else echo \"${GITHUB_REF#refs/tags/}\"; fi)"
      - name: Get artifact
        uses: actions/download-artifact@v1
        with:
          name: static-assets
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: Deploy to S3
        run: >
          aws s3 sync --delete --cache-control 'max-age=300' --metadata $'{"x-content-type-options": "nosniff", "permissions-policy": "accelerometer=(), ambient-light-sensor=(), autoplay=(), battery=(), camera=(), display-capture=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), midi=(), picture-in-picture=(), sync-xhr=(), usb=(), vr=(), wake-lock=(), screen-wake-lock=(), web-share=(), xr-spatial-tracking=()", "referrer-policy": "no-referrer-when-downgrade", "strict-transport-security": "max-age=31536000", "x-frame-options": "SAMEORIGIN", "content-security-policy": "default-src \'self\'; frame-src https://*.live.plugins.dev; img-src \'self\' www.googletagmanager.com data:; script-src \'self\' https://live.plugins.dev https://www.googletagmanager.com; script-src-elem \'self\' https://live.plugins.dev https://www.googletagmanager.com; style-src \'self\' https://fonts.googleapis.com \'unsafe-inline\'; style-src-elem \'self\' https://fonts.googleapis.com \'unsafe-inline\'; form-action \'self\' https://ratchetdesigns.us4.list-manage.com; object-src \'none\'; connect-src \'self\' https://www.google-analytics.com; frame-ancestors \'self\'; font-src \'self\' https://fonts.gstatic.com", "cross-origin-embedder-policy": "require-corp", "cross-origin-opener-policy": "same-origin", "cross-origin-resource-policy": "same-origin"}' . s3://docs.plugins.dev/${{ steps.destination.dest }}
        working-directory: static-assets
